apiVersion: apps/v1
kind: Deployment
metadata:
  name: leet-code-url-shortener
  labels:
    app: leet-code-url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leet-code-url-shortener
  template:
    metadata:
      name: leet-code-url-shortener
      labels:
        app: leet-code-url-shortener
    spec:
      containers:
        - name: leet-code-url-shortener
          image: leet-code/url-shortener
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      